baseURL = "https://laughing-liskov-db83d0.netlify.com/"
languageCode = "en-us"
summarylength = 25
disqusShortname = "www-dcotterill-com"
googleAnalytics = "UA-75580297-1"


[params]
    title = "Darren Cotterill"
    subtitle = "My Current Passions"

[menu]

    [[menu.main]]
        identifier = "home"
        name="Home"
        url="/"
        weight = 10

    [[menu.main]]
        identifier = "why?"
        name="Why?"
        url="/why"
        weight=40

    [[menu.main]]
        identifier = "blog"
        name="Blog"
        url="/blog"
        weight=40

    [[menu.main]]
        identifier = "about"
        name="About-Me"
        url="/about-me"
        weight=60

    [[menu.main]]
        identifier = "contact"
        name="Contact"
        url="/contact"
        weight=60
